# Generated by Django 2.1.4 on 2018-12-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_requests',
            name='author',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='author',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
