# Generated by Django 2.1.2 on 2019-01-05 19:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_portal', '0002_auto_20190105_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_requests',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
