# Generated by Django 2.1.4 on 2018-12-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_portal', '0003_auto_20181214_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_requests',
            name='upvote_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
