# Generated by Django 2.1.4 on 2018-12-14 01:49

from django.db import migrations, models
import member_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('member_portal', '0004_auto_20181214_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_requests',
            name='dev_response',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feed_requests',
            name='downvoters',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feed_requests',
            name='sshots',
            field=models.ImageField(default=None, null=True, upload_to=member_portal.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='feed_requests',
            name='upvoters',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='dev_response',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='downvoters',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='sshots',
            field=models.ImageField(default=None, null=True, upload_to=member_portal.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='upvoters',
            field=models.TextField(default=None, null=True),
        ),
    ]
