# Generated by Django 2.1.4 on 2018-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_portal', '0005_auto_20181214_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_requests',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
