# Generated by Django 2.1.4 on 2018-12-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_portal', '0006_auto_20181217_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed_requests',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
