# Generated by Django 2.1.4 on 2018-12-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_portal', '0008_auto_20181217_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed_requests',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='feed_requests',
            name='dev_response',
        ),
        migrations.RemoveField(
            model_name='feed_requests',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='feed_requests',
            name='downvoters',
        ),
        migrations.RemoveField(
            model_name='feed_requests',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feed_requests',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='feed_requests',
            name='upvoters',
        ),
    ]
