# Generated by Django 2.1.4 on 2018-12-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Android',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('publisher', models.CharField(default=None, max_length=300)),
                ('app_url', models.TextField(default=None)),
                ('pub_url', models.CharField(default=None, max_length=300)),
                ('cover', models.TextField(default=None)),
                ('price', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
