# Generated by Django 2.1.2 on 2019-01-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_uwp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uwp',
            name='publisher_url',
        ),
    ]
